language: python
sudo: false

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

addons:
  apt:
    packages:
      - libpcsclite-dev
      - swig

install:
    - pip install -r dev-requirements.txt
    - pip install .

script:
    - coverage run setup.py test

after_success:
    - coveralls
