language: python
sudo: required

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libpcsclite-dev swig

install:
    - pip install -r dev-requirements.txt
    - pip install .

script:
    - coverage run setup.py test

after_success:
    - coveralls
